name = "kanban-flow"
main = ".open-next/worker.js"
compatibility_date = "2025-04-20"
compatibility_flags = [ 
  "nodejs_compat"
]

# Bind a KV namespace for Next.js cache (required by OpenNext)
[[kv_namespaces]]
binding = "KV_CACHE"
id = "aab9cadac18e4ff5a7892b0b6dfd82e1"

# Bind an R2 bucket for Next.js incremental cache (required by OpenNext)
[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "kanban-flow-inc-cache"

[[d1_databases]]
binding = "DB"
database_name = "kanban-flow-auth"
database_id = "64813cff-2067-4808-94c2-6c55407d0324"

# Static asset handling
[assets]
directory = ".open-next/assets"

# Configure public environment variables (non-sensitive only)
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_SUPABASE_URL = "https://eehnntuxrpwoyxfrbimo.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlaG5udHV4cnB3b3l4ZnJiaW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzczNTEsImV4cCI6MjA2MDcxMzM1MX0.EHLxEEQ0vx7_8Xn0j1k3u2j30dT1COjWFYaGAvfDLuk"

# Rules for ESModule handling (required for modern Next.js)
rules = [{ type = "ESModule", globs = ["**/*.js", "**/*.mjs"] }]

# Configure custom domain
[[routes]]
pattern = "tasks.feistyagency.com"
custom_domain = true

# Add warm-up cron to reduce cold starts
[triggers]
crons = ["*/10 * * * *"]

# Memory limit (increases performance but costs more)
[limits]
cpu_ms = 10
memory_mb = 128
